### PR TITLE
For those who has email aliases like firstname.lastname@domain

### PR DESCRIPTION
**Pull request by jazzl0ver**

### CODE REVIEW

**Comment by LarsGit223** [comment]
How do you now the e-mail alias has the separator '.'? Shouldn't there be an option to specify ```.```, ```-``` or ```_``` as the separator.

**Comment by jazzl0ver** [comment]
Well, this is what we have in our company

**Comment by LarsGit223** [comment]
I implemented a more flexible solution, see #5. What do you think about it?

**Comment by jazzl0ver** [comment]
I think it's awesome :)

**Comment by LarsGit223** [comment]
Good. I merged #5 so this can be closed.

**Pull request closed without merging**
